### ISSUE TITLE
Clicking the Username of people in the My Posts section redirects to a wrong page instead of the correct User ID

### ISSUE THREAD

**Issue by PeePeePooPooDiarrhea** [Brick-Hill-Co/Brick-Hill-Bug-Tracker#11]
Minor severity

![Screenshot_20240121-142409_Opera](https://github.com/Brick-Hill-Co/Brick-Hill-Bug-Tracker/assets/150975644/e7f9c3c3-df82-45de-b251-e6e84f646290)
![Screenshot_20240121-142414_Opera](https://github.com/Brick-Hill-Co/Brick-Hill-Bug-Tracker/assets/150975644/473d8865-9cca-47a9-a2a3-45364749781a)

Click one of the usernames in your My posts section to replicate

Hourjiwara

**Comment by whtepony** [comment]
Fixed.
