### ISSUE TITLE
Clan rank name issues.

### ISSUE THREAD

**Issue by obesefatrabbit** [Brick-Hill-Co/Brick-Hill-Bug-Tracker#2]
Whenever I change the name of a rank or change the power it has, it brings me to the login page but when I go back to the clans tab, im still logged in.

How to replicate it: Go to edit a clan you own then change the power or name of a ranking you already have. Once you press save, it should bring you to the login page, yet you are actually still logged in.

My username is obese fat rabbit. This bug is normal, not too severe.

**Comment by whtepony** [comment]
This will be fixed in our new update, I will keep this open until I fix it.

**Comment by whtepony** [comment]
WIll be fixed when I rewrite
