### ISSUE TITLE
Redirection to OG brick hill by changing power in clans

### ISSUE THREAD

**Issue by ThedopestKira** [Brick-Hill-Co/Brick-Hill-Bug-Tracker#3]
When changing the power level of owner in a clan it redirects you to OG brick hill, not severe but quite an annoying bug

Steps
Go to your clan, edit it, edit owner rank make it under 100 and it will redirect you to OG brick hill

Name onsite: ClockWork

**Comment by whtepony** [comment]
WIll be fixed when I rewrite
