### ISSUE TITLE
Https:// links on bhco

### ISSUE THREAD

**Issue by obesefatrabbit** [Brick-Hill-Co/Brick-Hill-Bug-Tracker#5]
So, I posted on a forum a clothing link that I made, and it turns out it turned the the :/ part of the link to the emoticon version of :/

How to replicate it: Go to a forum post and put a random https:// link and then it will turn the :/ into an emoticon.

This is a normal bug.

My user is obese fat rabbit.

**Comment by Orio-nn** [comment]
I will close this issue for now since we have temporarily removed the emote that was causing the issue.
